### ISSUE TITLE
righttriangle.cpp only takes in metric inputs

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/random_c_cpp_programs#1]
The righttriangle.cpp program I made will only accept metric inputs.  Fine considering most of the world uses metric but this would not be good in areas where metric is not, like the US.

Make this not only accept metric but also SI units like inches.

**Comment by Wolfmyths** [comment]
Hello I would like to work on this but I have a question for this issue.

Should we let the user type in any unit of measurement defined in a string instead?

**Comment by gbowne1** [comment]
ok.  I think that would be fine.  I think otherwise it might need to do some unit conversion.  

Say the user typed in 3.982mm in X and 93.982mm in Y  

Note: I also couldnt get it to take in the Y value. It outputs 0 no matter what. iirc.

I assigned you to this.

**Comment by Wolfmyths** [comment]
What I meant was that before the user gets to choose the variables, they are given a new prompt to type out the unit of measurement they want to use. which will then be used throughout the rest of the prompts. Assuming that the user is using the same unit of measurement for all variables.

I'll post the PR to show what I am talking about

**Comment by gbowne1** [comment]
well, that sounds good enough to me. I have a few more programs I forgot to add.
