### ISSUE TITLE
/cpp_programs/winsize.cpp works but doesn't count characters in the row

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/random_c_cpp_programs#23]
It's able to print the string of characters across the terminal/shell/console, etc. but it doesn't count them.

**Comment by noah-white-8** [comment]
Is this still open? How could I go about contributing? I'm a newbie.

**Comment by gbowne1** [comment]
If it's still in the list, it's open. For clarity, Are you new to contributing or just C/C++?

I can assign you to the issue if you would like to contribute.  If not, that's ok.

**Comment by amgodoi** [comment]
Hi @gbowne1,

How can I contribute?

I am not a C/C++ programmer anymore (last time was in 2010).
I am a git user, but not a github user.

**Comment by gbowne1** [comment]
Ok. Most of my programs here are either math or electronics related with a few exceptions. Feel free to work on this issue or any others here.  Let me know what you would like to do.  

You can clone or fork this project/repository.

Thanks @amgodoi

**Comment by amgodoi** [comment]
Forked and Cloned!

Any idea do help?

Any bug fix? Any small feature?

I would like to do some change and create a pull request.

**Comment by gbowne1** [comment]
If you would like to, feel free to test the programs, debug, add features, etc 

All is welcome.. especially testing out programs for bugs, issues, errors, warnings, etc. And testing with different compilers and compiler settings.

If you feel like there's an issue then feel free to bug report or make an issue on github here...

Thanks @amgodoi
