### ISSUE TITLE
[ToDo] Add Wattage calculation to resistorcolor.c and/or resistance.c 

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/random_c_cpp_programs#34]
So:

Typical values for a 1/2 watt or 1/4 watt resistor (typical/common sizes) refer to their power ratings and the current or voltage they can safely handle without overheating. The power rating of a resistor indicates how much power it can dissipate in the form of heat. This is calculated using the formula ( P = I^2R ) where ( P ) is power in watts, ( I ) is current in amperes, and ( R ) is resistance in ohms.

    For a 1/4 watt resistor, the maximum current ( I_{1/4W} ) can be calculated by rearranging the formula to:
    
     ( I = \sqrt{\frac{P}{R}} ), and substituting ( P = 0.25 ) watts. 
     
     So the maximum current for a 1/4 watt resistor is ( \sqrt{\frac{0.25}{R}} ) amps.
   
    For a 1/2 watt resistor, the maximum current ( I_{1/2W} ) is ( \sqrt{\frac{0.5}{R}} ) amps.

Using these formulas, we can calculate the maximum current a resistor can handle based on its power rating and resistance value.

For example, if you have a 100-ohm resistor:

    The maximum current for a 1/4 watt resistor would be ( \sqrt{\frac{0.25}{100\Omega}} = 50\ mA )
    The maximum current for a 1/2 watt resistor would be ( \sqrt{\frac{0.5}{100\Omega}} = 100\ mA )

**Comment by bloemenk** [comment]
HI @gbowne1, Hi Gregory

As an electromechanical engineer, this topic suits me very well. Can I please contribute to this issue?

Best regards,

Koen

**Comment by gbowne1** [comment]
yes you can contribute if you wish. I can assign you to this if you like.

thanks @bloemenk

**Comment by bloemenk** [comment]
I have created a pull request. I have build up both functions to calculate the maximum current allowed based on a given wattage and resistance. Please let me know if this is not what you want.

regards,

Koen
