### ISSUE TITLE
Some issues with lowpassfil.c and it also will not compile without using -lm to link in gcc

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/random_c_cpp_programs#4]
There are a few issues with lowpassfil.c 

I have not tried other compilers but:

```shell
$ gcc -o lowpassfil lowpassfil.c
/usr/bin/ld: /tmp/ccOAOOQU.o: in function `calculateGain':
lowpassfil.c:(.text+0x65): undefined reference to `pow'
/usr/bin/ld: lowpassfil.c:(.text+0x7a): undefined reference to `sqrt'
/usr/bin/ld: /tmp/ccOAOOQU.o: in function `calculateAttenuation':
lowpassfil.c:(.text+0xbf): undefined reference to `pow'
/usr/bin/ld: lowpassfil.c:(.text+0xd4): undefined reference to `log10'
collect2: error: ld returned 1 exit status
```

while `gcc -o lowpassfil lowpassfil.c -lm` just works.

Also, 

Here is the output if you are able to compile with -lm

```shell
$ ./lowpassfil
Cutoff Frequency: 15.915494 Hz
Gain: 0.031815
Attenuation: -29.947396 dB
Calculated Resistor: 1000.000000 ohms
Calculated Capacitor: 1.000000e-05 farads
Calculated Inductance: 1.000000e+03 henrys
```

When I made this, it just used predefined constant values. This program needs to accept user input values.

**Comment by andrewlod** [comment]
Hello!
The `-lm` flag is needed in GCC in order to link the `math.h` library (libm.a), which contains such functions (`pow`, `sqrt`, `log10`).
I hope this helps :)

**Comment by gbowne1** [comment]
thats what I was thinking.  Thanks @andrewlod
