### ISSUE TITLE
gradebook.c program issues

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/random_c_cpp_programs#6]
This may need to be refactored.

I tried making a C++ gradebook program for the US K-12 grades that used .csv files

It's incomplete and has lots of bugs.

the .csv, .h and .cpp file are included for this application.  

It needs to be able to load and and parse the .csv files.

**Comment by andrewlod** [comment]
Hello!
Could you please provide the structure of the CSV files, such as header, and a few instances? Depending on the structure of the CSV file, there may be different optimal solutions.
As far as I can tell, the structure is `student_name,grade_1,grade_2,grade_3...`, however, the structure `Grade` has an attribute `name`, which is not used.
Thank you!

**Comment by gbowne1** [comment]
@andrewlod 

I got started on this a while back and lost track of where I was going with it.  This really should have multiple csv files.. but..

as for Student Data: Each student's data would be stored in a separate row of the CSV file. Columns could include student ID, name, grade level, teacher's name, class/subject name, and GPA. Attendance records, behavioral reports, special needs information, parent communication logs, assignment details, conduct grades, additional assessment scores, comments, and observations could be stored in separate rows or in a separate CSV file linked by the student ID.

I thought about std::map where the key is the student ID and the value is a struct containing the rest of the student data. This would allow for efficient lookup of student data by ID.

 We could structure the CSV files as follows:

    Students CSV: This file would contain basic student information. Columns could include Student ID, Name, Grade Level, and GPA.

    Teachers CSV: This file would hold data about the teachers. Columns could include Teacher ID, Name, and any other relevant information.

    Classes CSV: This file would contain details about the classes. Columns could include Class ID, Class Name, Grade Level, and Teacher ID.

    Assignments CSV: This file would store information about the assignments. Columns could include Assignment ID, Class ID, Assignment Name, Due Date, and any other relevant information.

    Grades CSV: This file would link students, assignments, and their grades. Columns could include Student ID, Assignment ID, and Grade.

    Attendance CSV: This file would track student attendance. Columns could include Student ID, Date, and Attendance Status.

    Behavior CSV: This file would record behavioral incidents. Columns could include Student ID, Date, Incident Description, and any other relevant information.

    Notes CSV: This file would store any additional notes about a student. Columns could include Student ID, Date, Note, and any other relevant information.

Each CSV file should have a header row that describes what each column represents. The data in each row should correspond to a single record. We then can use unique identifiers (like Student ID, Teacher ID, Class ID, etc.) to link data across different CSV files.

**Comment by andrewlod** [comment]
Since we are going to be handling with multiple CSV files, I think that it would be useful to create a data structure that reads from CSV files and stores data into a sort of matrix, similar to [Pandas DataFrame](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html). This is the sort of structure I came up with:
```cpp
class DataFrame {
private:
    std::vector<std::string> header;
    std::map<std::string, std::vector<std::string>> data;
public:
    DataFrame();
    DataFrame(const std::string &fileName);

    // Access a row
    std::map<std::string, std::string*> operator[](size_t index);

    // Access a column
    std::vector<std::string> &operator[](const std::string &key);

    // Collection operations
    size_t sizeRows();
    size_t sizeCols();
    void clear();
    void append(const std::map<std::string, std::string> &row);
    void remove(size_t index);

    // I/O operations
    int load(const std::string &fileName);
    int save(const std::string &fileName);
};
```
It allows loading a CSV file as well as writing it, and I took advantage of the operator[] overload to handle data access and modification. If you pass a string to operator[] (such as `dataframe["student_name"]`), you will get all available values for that key, while if you pass an index (`dataframe[0]`), it will return a row of the CSV file, as a map of string pointers. Of course you can mix those two, such as `dataframe["student_name"][0]`, where you will get the name of the first student in the data structure.

As for your idea of identifying resources (students, teachers, classes) by the ID, I think it is great, as unique IDs are a great alternative for using names, where they can be misspelled and lead to errors. These kinds of IDs are widely used on relational databases.

**Comment by gbowne1** [comment]
@andrewlod 

Yeah I agree with that too.  That would be very useable. I like that idea.

**Comment by andrewlod** [comment]
I could start working on that, if you don`t mind!

**Comment by gbowne1** [comment]
By all means, feel free to do so.

**Comment by gbowne1** [comment]
A few things:

- How hard would it be to print the data in tables?
- To be really useful, especially in a real situation, this should have a complete menu system.
- I only have a older cmake.  Haven't updated yet.  I had to change the version to 3.0.
- There's now a folder with gradebook in it.  But the original files exist in the root of /cpp_programs still.
- Running the make built it just fine.

```shell
gbowne1@gregbowne:~/Documents/random_c_cpp_programs/cpp_programs/gradebook
$ cmake -B build
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/gbowne1/Documents/random_c_cpp_programs/cpp_programs/gradebook/build

Build worked fine..

gbowne1@gregbowne:~/Documents/random_c_cpp_programs/cpp_programs/gradebook
$ cd build


gbowne1@gregbowne:~/Documents/random_c_cpp_programs/cpp_programs/gradebook/build
$ make
Scanning dependencies of target gradebook
[ 33%] Building CXX object CMakeFiles/gradebook.dir/gradebook.cpp.o
[ 66%] Building CXX object CMakeFiles/gradebook.dir/dataframe.cpp.o
[100%] Linking CXX executable gradebook
[100%] Built target gradebook
gbowne1@gregbowne:~/Documents/random_c_cpp_programs/cpp_programs/gradebook/build

Running the gradebook it built:

$ ./gradebook
Insert student ID for average score calculation: 0001
Average score for student ID 1: 0
```

**Comment by gbowne1** [comment]
A menu might look like: 

```cpp
int main()
{
    int choice;
    while (true)
    {
        std::cout << "1. Load Grades\n";
        std::cout << "2. Save Grades\n";
        std::cout << "3. Add Student\n";
        std::cout << "4. Remove Student\n";
        std::cout << "5. Exit\n";
        std::cout << "Choose an option: ";
        std::cin >> choice;

        switch (choice)
        {
            case 1:
                load_grades();
                break;
            case 2:
                save_grades();
                break;
            case 3:
                add_student();
                break;
            case 4:
                remove_student();
                break;
            case 5:
                return 0;
            default:
                std::cout << "Invalid choice. Try again.\n";
        }
    }
}
```

**Comment by andrewlod** [comment]
About those questions:
> * How hard would it be to print the data in tables?

I don't think it would be hard at all. All the data is already in the structs created, and there is no nesting. It is just a matter of iterating the maps and printing it in a nice format.

> * To be really useful, especially in a real situation, this should have a complete menu system.

I have seen your menu example and it is pretty easy to implement, now that the core part is done. I will do it whenever I have some free time.

> * I only have a older cmake.  Haven't updated yet.  I had to change the version to 3.0.

No worries, you can change the CMake version to 3.0. I have specified 3.22 because it was my own version, but it is a rather simple program with no libraries or newer C++ features.

> * There's now a folder with gradebook in it.  But the original files exist in the root of /cpp_programs still.

Strange... I had moved the files into a folder, since the project is slightly more complex than the others, with a bunch of files, it would make sense to put them all in a folder. Maybe the merge with the main repository had kept the old files. I will remove them when I work on it.

> * Running the make built it just fine.

Nice! The build & run should be really simple:
```sh
mkdir build
cd build
cmake ..
make
./gradebook
```

**Comment by gbowne1** [comment]
@andrewlod 

I usually do 3.0 because before that was a whole different cmake and I never know what version people have.

I have a whole pile of old programs in a old binder notebook on paper I will be adding so make sure to stay synced with the main branch. 

I originally intended to have the gradebook be actually useable in a real environment.  At some point it might be worth it to extract the program from this into its own repo.

I originally wrote this for the IBM PC, PC/XT and PS/2 and AT machines we had at the time.

**Comment by gbowne1** [comment]
I do cmake -B build which creates a build  folder and runs the build process. Might be worthwhile to fancy up the CMakeLists.txt

A lot of the programs I wrote over the past 29 years or so were math related or calculate certain things in electronics, etc.

**Comment by andrewlod** [comment]
> I do cmake -B build which creates a build folder and runs the build process. Might be worthwhile to fancy up the CMakeLists.txt
That works as well. By fancying up, do you mean adding comments, project description, version etc?

**Comment by gbowne1** [comment]
yes, at some point.

**Comment by gbowne1** [comment]
Just a note: there is still a studentdata.csv in /cpp_programs/studentdata.csv even after merges.  I will fix that.

**Comment by gbowne1** [comment]
@andrewlod  

I think at some point to also build for Darwin and Windows becuase I can imagine some schools, districts, etc. will want to run this in different environments.

**Comment by andrewlod** [comment]
I will take that into consideration. I know little about Darwin, but my biggest concern about Windows is that while Unix uses `std::string`, Windows uses `std::wstring` (2x wide string). CPPRestSDK for example takes wstring parameters on Windows and string on Unix.

**Comment by gbowne1** [comment]
maybe just add some conditionals?  I've also never cross compiled using CMake.

Probably not too far off of extracting this into a new repo.

**Comment by andrewlod** [comment]
Many libraries get around these OS issues with `typedef`, for example:

```cpp
#if defined(UNIX)
typedef std::string gb_string;
#elif defined(WIN32)
typedef std::wstring gb_string;
#endif
```

Something like that, so we would use `gb_string` instead of normal strings

**Comment by gbowne1** [comment]
yeah. that would work too.  I've seen this used before.

**Comment by gbowne1** [comment]
@andrewlod  I have made a new repository

https://github.com/gbowne1/gradebook-management-system

Should be reasonably complete. Figured it was about time.

I will leave this here for the time being.. just in case.
